/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

/**
 *
 * @author Alvaro Zahid Postigo Chumacero
 */
import servicio.ProductoServicio;
import servicio.PedidoServicio;
import servicio.TareaServicio;
import modelo.Usuario;

public class Inicio extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Inicio.class.getName());

    // Servicios compartidos por toda la aplicación (singletons).
    private static final TareaServicio tareaService;
    private static final ProductoServicio productoService;
    private static final PedidoServicio pedidoService;

    // Bloque de inicialización estático para configurar los servicios solo una vez
    static {
        tareaService = new TareaServicio();
        productoService = new ProductoServicio("productos.xml");
        pedidoService = new PedidoServicio("pedidos.xml", tareaService);
    }

    /*Usuario autenticado en la aplicación. Según su rol se habilitan
     determinadas opciones en el menú. */
    private Usuario usuario;

    public Inicio() {
        initComponents();
        setLayout(null);
        setLocationRelativeTo(null);
        setResizable(false);

        //Accionamiento de los botones 
        btnGestionProductos.addActionListener(evt -> abrirGestionProductos());
        btnGestionPedidos.addActionListener(evt -> abrirGestionPedidos());
        btnGestionTareas.addActionListener(evt -> abrirGestionTareas());
        btnCerrarSesion.addActionListener(evt -> cerrarSesion());

    }

    /*
     Constructor que recibe el usuario autenticado y configura el menú
     principal según su rol.
     */
    public Inicio(Usuario usuario) {
        this();
        this.usuario = usuario;
        configurarAccesosPorRol();
    }

    /* Abre la ventana de gestión de productos, oculta el menú principal
     y comparte las mismas instancias de servicio.*/
    private void abrirGestionProductos() {
        FrameGestionProductos frm = new FrameGestionProductos(productoService, this);
        frm.setVisible(true);
        this.setVisible(false);
    }

    // Abre la ventana de gestión de pedidos con los servicios necesarios.
    private void abrirGestionPedidos() {
        FrameGestionPedidos frm = new FrameGestionPedidos(pedidoService, productoService, this);
        frm.setVisible(true);
        this.setVisible(false);
    }

    /* Abre la ventana de gestión de tareas. El pedidoService es
     indispensable para poder marcar los pedidos como ENVIADO cuando se
     procesa una tarea. */
    private void abrirGestionTareas() {
        FrameGestionTareas frm = new FrameGestionTareas(tareaService, pedidoService, this);
        frm.setVisible(true);
        this.setVisible(false);
    }

    //Configura la visibilidad de los botones del menú según el rol del usuario autenticado. 
    private void configurarAccesosPorRol() {
        if (usuario == null) {

            btnGestionProductos.setEnabled(true);
            btnGestionPedidos.setEnabled(true);
            btnGestionTareas.setEnabled(true);
            return;
        }
        String rol = usuario.getRol();
        if (rol != null && rol.equalsIgnoreCase("USUARIO")) {
            btnGestionProductos.setEnabled(true);
            btnGestionPedidos.setEnabled(true);
            btnGestionTareas.setEnabled(false);
        } else if (rol != null && rol.equalsIgnoreCase("ADMIN")) {
            btnGestionProductos.setEnabled(false);
            btnGestionPedidos.setEnabled(false);
            btnGestionTareas.setEnabled(true);
        } else {

            btnGestionProductos.setEnabled(false);
            btnGestionPedidos.setEnabled(false);
            btnGestionTareas.setEnabled(false);
        }
    }

    //Regresa al login.
    private void cerrarSesion() {

        this.dispose();

        Login login = new Login();
        login.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnGestionProductos = new javax.swing.JButton();
        btnGestionPedidos = new javax.swing.JButton();
        btnGestionTareas = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 102));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));

        jLabel2.setFont(new java.awt.Font("Serif", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistema de Gestión de Pedidos y Tareas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnGestionProductos.setBackground(new java.awt.Color(51, 0, 0));
        btnGestionProductos.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnGestionProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionProductos.setText("Gestión de Productos");
        btnGestionProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionProductosActionPerformed(evt);
            }
        });

        btnGestionPedidos.setBackground(new java.awt.Color(51, 0, 0));
        btnGestionPedidos.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnGestionPedidos.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionPedidos.setText("Gestión de Pedidos");

        btnGestionTareas.setBackground(new java.awt.Color(51, 0, 0));
        btnGestionTareas.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnGestionTareas.setForeground(new java.awt.Color(255, 255, 255));
        btnGestionTareas.setText("Gestión de Tareas");

        btnCerrarSesion.setBackground(new java.awt.Color(51, 0, 0));
        btnCerrarSesion.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Volver al Login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGestionProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionTareas, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnGestionProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGestionPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGestionTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarSesion)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGestionProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestionProductosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGestionPedidos;
    private javax.swing.JButton btnGestionProductos;
    private javax.swing.JButton btnGestionTareas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
